name: CI Build
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build_and_tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11' ]
    steps:
      # Setup Java & Python
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Checkout icat-autnetication
        uses: actions/checkout@v2

      - name: Run Build
        run: mvn install -DskipTests
